spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?password=password&useSSL=false&allowPublicKeyRetrieval=true
    username: root
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
