logging:
  level:
    root: INFO

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp